### ISSUE TITLE
Possible errors in vector numbers

### ISSUE THREAD

**Issue by dirkbruere** [vancegroup-mirrors/avr-libc#2]
https://github.com/vancegroup-mirrors/avr-libc/blob/master/avr-libc/include/avr/iocanxx.h 
The vector numbers in this do not match the vector numbers in the manual AT90CAN128 doc7679 pdf Section 8.1
They appear to be one position out
Can you advise on which is correct?

**Comment by rpavlik** [comment]
This is not the upstream.
