### ISSUE TITLE
This automated mirror is very old

### ISSUE THREAD

**Issue by drf5n** [vancegroup-mirrors/avr-libc#4]
The http://svn.savannah.gnu.org/viewvc/avr-libc/ site has it at release 2.1.0 for Fri Jan 28 23:10:52 2022 UTC  while this mirror advertises 7 years old:

http://svn.savannah.gnu.org/viewvc/avr-libc?view=revision

Many documentation changes have happened since then.

Could you freshen the automatic mirror?

**Comment by drf5n** [comment]
In June 2024, the current avr-libc work moved from http://svn.savannah.gnu.org/viewvc/avr-libc/ to:

https://github.com/avrdudes/avr-libc

Look there for more recent development.

**Comment by rpavlik** [comment]
thanks for the update. It's been a decade since I was in grad school and was able to maintain this mirror :grinning: . Kind of surprised it took so long for them to move to git...
